### ISSUE TITLE
FlashAttention？

### ISSUE THREAD

**Issue by BridgetteSong** [xingchensong/S3Tokenizer#15]
`MultiHeadAttention`中使用[FlashAttention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html)是否会更快一点？直接替换可以保证计算准确度吗？

**Comment by Mddct** [comment]
可以参考wenet里边是怎么集成sdpa的

**Comment by Mddct** [comment]
@BridgetteSong  https://github.com/xingchensong/S3Tokenizer/pull/27
