### ISSUE TITLE
Cosyvoice2.0 is released!

### ISSUE THREAD

**Issue by lastapple** [xingchensong/S3Tokenizer#16]
Are you interested in doing reverse engineering for [the v2 tokenizer](https://www.modelscope.cn/models/iic/CosyVoice2-0.5B/files) ？

**Comment by xingchensong** [comment]
Yes, don't worry, I'll do it when I'm free these two days.

**Comment by xingchensong** [comment]
https://github.com/xingchensong/S3Tokenizer/pull/18

**Comment by Mddct** [comment]
> #18

it works ! in  https://github.com/xingchensong/S3Tokenizer/pull/18

**Comment by xingchensong** [comment]
pip install -U S3Tokenizer

**Comment by lastapple** [comment]
世上还是好人多啊QAQ老哥你开直播吧我给你刷火箭

**Comment by Alidaling** [comment]
> > #18
> 
> it works ! in #18

Thank you for sharing. However, why does it report the following error when I load the speech_tokenizer_v2_25hz version? The model used is S3TokenizerV2, and the onnx is the speech_tokenizer_v2.onnx provided by the official. Could you please tell me where the problem lies?
![企业微信截图_17349520661548](https://github.com/user-attachments/assets/b8daed83-70f4-4b6e-b208-8bc3db8d0e3e)

**Comment by xingchensong** [comment]
cc @Mddct

**Comment by lastapple** [comment]
> > > #18
> > 
> > 
> > it works ! in #18
> 
> Thank you for sharing. However, why does it report the following error when I load the speech_tokenizer_v2_25hz version? The model used is S3TokenizerV2, and the onnx is the speech_tokenizer_v2.onnx provided by the official. Could you please tell me where the problem lies? ![企业微信截图_17349520661548](https://private-user-images.githubusercontent.com/131933121/398143380-b8daed83-70f4-4b6e-b208-8bc3db8d0e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjYwMDIsIm5iZiI6MTczNTAyNTcwMiwicGF0aCI6Ii8xMzE5MzMxMjEvMzk4MTQzMzgwLWI4ZGFlZDgzLTcwZjQtNGI2ZS1iMjA4LThiYzNkYjhkMGUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNzM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzc0NmZhOWU2N2M1NjNhZDJlMzJiYmNmMzhiOTQwMjFkOWMyMTg2NmE2NWNjYjQ1YWI4N2RiOTc4ZWVjNDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j94edB4ZfTZOla6nnWWDRNvV_ikKHBnuoTSZ_01knZc)

I feel very convenient to use and haven't encountered this problem. Maybe you can check if your s3tokenizer code is up-to-date?

**Comment by Alidaling** [comment]
> > > > #18
> > > 
> > > 
> > > it works ! in #18
> > 
> > 
> > Thank you for sharing. However, why does it report the following error when I load the speech_tokenizer_v2_25hz version? The model used is S3TokenizerV2, and the onnx is the speech_tokenizer_v2.onnx provided by the official. Could you please tell me where the problem lies? ![企业微信截图_17349520661548](https://private-user-images.githubusercontent.com/131933121/398143380-b8daed83-70f4-4b6e-b208-8bc3db8d0e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjYwMDIsIm5iZiI6MTczNTAyNTcwMiwicGF0aCI6Ii8xMzE5MzMxMjEvMzk4MTQzMzgwLWI4ZGFlZDgzLTcwZjQtNGI2ZS1iMjA4LThiYzNkYjhkMGUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNzM1MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzc0NmZhOWU2N2M1NjNhZDJlMzJiYmNmMzhiOTQwMjFkOWMyMTg2NmE2NWNjYjQ1YWI4N2RiOTc4ZWVjNDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j94edB4ZfTZOla6nnWWDRNvV_ikKHBnuoTSZ_01knZc)
> 
> I feel it very convenient to use and haven't encountered this problem. Maybe you can check if your s3tokenizer code is up-to-date?

I'm using the latest S3Tokenizer. However, the speech_tokenizer_v2.onnx is provided by the official of Cosyvoice2 instead of being automatically downloaded by S3Tokenizer (it couldn't be automatically downloaded due to certain reasons). Could this be related?
![企业微信截图_17350320704462](https://github.com/user-attachments/assets/74bd0c25-f1cc-4044-8a27-4332b93c194a)

**Comment by xingchensong** [comment]
![image](https://github.com/user-attachments/assets/a1a763a8-fbd6-4228-881a-087a25e951f6)

官方12.17更新过onnx

**Comment by Alidaling** [comment]
> ![image](https://private-user-images.githubusercontent.com/13466943/398691113-a1a763a8-fbd6-4228-881a-087a25e951f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyODk2NTksIm5iZiI6MTczNTI4OTM1OSwicGF0aCI6Ii8xMzQ2Njk0My8zOTg2OTExMTMtYTFhNzYzYTgtZmJkNi00MjI4LTg4MWEtMDg3YTI1ZTk1MWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDA4NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1Y2M5YmRlZDE0MzYxNzI4YWI2OWViMjgxYjRkY2ZhZDMzZjYwMmYwYWRmOTYzNmU0ZmMzN2U5MzcwNWQyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qF1y-G8R0f4G0_0mThxdFATklfKDn9R4kqh0tyUA1ig)
> 
> 官方12.17更新过onnx，本仓库用的是最新的onnx

原来如此！我重新下载了更新后的模型，确实没有问题了，感谢!
