### ISSUE TITLE
离线加载Cosyvoice2-0.5B/speech_tokenizer_v2.onnx报错

### ISSUE THREAD

**Issue by ystong** [xingchensong/S3Tokenizer#23]
感谢作者的辛苦工作，在使用0.1.2版本代码时，离线加载Cosyvoice2-0.5B/speech_tokenizer_v2.onnx报错，显示Errror(s) in loading state_dict for S3TokenizerV2: Missing keys in state_dict

**Comment by xingchensong** [comment]
下最新的onnx

**Comment by xingchensong** [comment]
![image](https://github.com/user-attachments/assets/7bffe62b-870e-4d8f-a00d-53f0fe473901)
官方12.17更新过onnx

**Comment by ystong** [comment]
可以了，十分感谢~
