### ISSUE TITLE
25hz的版本出来了，本仓库会支持25hz的s3token吗？

### ISSUE THREAD

**Issue by splinter21** [xingchensong/S3Tokenizer#5]
感谢repo主的贡献！好奇问一下

**Comment by xingchensong** [comment]
https://github.com/xingchensong/S3Tokenizer/pull/6

有时间可以帮忙验证下吗？

**Comment by Mddct** [comment]
25的这个 他也是release的onnx吗

**Comment by xingchensong** [comment]
是的

**Comment by splinter21** [comment]
> #6
> 
> 有时间可以帮忙验证下吗？

我没验效果，但是shape是对的，准备先训个TTS测一波，感谢楼主支持

**Comment by xingchensong** [comment]
@splinter21 有结果记得反馈下

**Comment by splinter21** [comment]
> @splinter21 有结果记得反馈下

使用s3token25hz的TTS模型是可以正常训练的
